### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by coldbootinitheart** [Magisk-Modules-Repo/mm#14]
Trying to install this module from within Magisk manager does not work. Log below
`- Copying zip to temp directory`
 `- Installing`
`Magisk_Manager_for_Recovery_Mode_(mm)-2019.4.4(201904040).zip`
`- Device is system-as-root`

`Magisk Manager for Recovery Mode (mm) 2019.4.4`
`Copyright (C) 2017-2019, VR25 @ xda-developers`
`License: GPLv3+`

`- Extracting module files `

`! Installation failed`

Using lineage OS 17.1 running on OnePlus 3. Busybox-ndk installed. Any help would be appreciated.

**Comment by Mibo5354** [comment]
PREREQUISITE: Magisk 17-19
Are you running Magisk 20 by any chance.

**Comment by coldbootinitheart** [comment]
I am using the latest Magisk version. I was under the assumption that it would work.

**Comment by ppjuns** [comment]
yes, I running in the Magisk v20 and failed

**Comment by Cyberavater** [comment]
I successfully installed it in TWRP. And it worked flawlessly.

**Comment by ghost** [comment]
> 
> 
> I am using the latest Magisk version. I was under the assumption that it would work.

that is it.the reason this module does not install on your device is your Magisk version is TOO NEW and the module did not updated since 4.4.2019
