### ISSUE TITLE
Mount failed 

### ISSUE THREAD

**Issue by ghost** [Magisk-Modules-Repo/mm#2]
- Copying zip to temp directory
- Installing Magisk_Manager_for_Recovery_Mode_(mm)-2018.8.1.zip
Archive:  /data/user/0/com.topjohnwu.magisk/cache/install.zip
  inflating: module.prop
 
Magisk Manager for Recovery Mode (mm) (mm) 2018.8.1
VR25 @ xda-developers
Powered by Magisk (@topjohnwu)
 
update-binary: line 192: make_ext4fs: not found
losetup: /data/adb/magisk_merge.img: No such file or directory
- Creating /data/adb/magisk_merge.img with size 64M
- Mounting /data/adb/magisk_merge.img to /dev/tmp/magisk_img
losetup: /data/adb/magisk_merge.img: No such file or directory
losetup: /data/adb/magisk_merge.img: No such file or directory
losetup: /data/adb/magisk_merge.img: No such file or directory
losetup: /data/adb/magisk_merge.img: No such file or directory
losetup: /data/adb/magisk_merge.img: No such file or directory
losetup: /data/adb/magisk_merge.img: No such file or directory
losetup: /data/adb/magisk_merge.img: No such file or directory
 
(!) /data/adb/magisk_merge.img mount failed... abort
 
! Installation failed

**Comment by Fingalzzz** [comment]
Kinda same here. Tried to install from Magisk installer but failed. 
Magisk v18.1
OnePlus A6013 OOS/Android 9.0.12

Log attached below.

- Copying zip to temp directory
- Installing Magisk_Manager_for_Recovery_Mode_(mm)-2018.8.1.zip

Magisk Manager for Recovery Mode (mm) (mm) 2018.8.1
VR25 @ xda-developers
Powered by Magisk (@topjohnwu)

- Creating /data/adb/magisk_merge.img with size 64M
- Mounting /data/adb/magisk_merge.img to /dev/tmp/magisk_img

(!) /data/adb/magisk_merge.img mount failed... abort

! Installation failed

**Comment by VR-25** [comment]
This is a Pie issue. It'll be fixed in the next version. Meanwhile, install from recovery.

**Comment by crok** [comment]
Magisk 19.0, MIUI 10 - Xiaomi.EU V10.2.2.0 (Nougat), Redmi Note 4X Snapdragon (Mido) - exactly the same happened to me. This is not a Pie-only issue.

**Comment by VR-25** [comment]
Magisk 19 is imageless. There's nothing to mount. That's the issue. I'm working on a major update.
